version: '3.1'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  web:
    build: ./src
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

  adminer_async:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    container_name: adminer_app_async
